MyChatGLA/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from chat import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('chat/', include('chat.urls')),
    path('admin/', admin.site.urls),
    path('', views.main_page), # needs to redirect to main page if logged in
    path('', include("allauth.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from chat import views

app_name = 'chat'

urlpatterns = [
    path('', views.main_page, name='chat'),
    path('create/', views.create_page, name='create'),
    path('auth/login/', views.user_login, name='login'),
    path('auth/logout/', views.user_logout, name='logout'),
    path('auth/signup/', views.sign_up, name='signup'),
    path('search_profiles/', views.search_profiles, name='search_profiles'),
    path('profile/', views.profile, name='profile'),
    path('test/', views.test, name='test'),
    path('chatroom/<slug:chat_name_slug>/', views.chat, name='chatroom'),
    path('chatroom/<slug:chat_name_slug>/leave', views.leave_group_chat, name='leave'),
    path('chatroom/<slug:chat_name_slug>/members', views.members, name='members'),
    path('chatroom/<slug:chat_name_slug>/files', views.files, name='files'),
    path('chatroom/<slug:chat_name_slug>/delete', views.delete_group_chat, name='delete'),
    path('chat/profile/delete_account', views.delete_account, name='delete_account'),
    path('chatroom/<slug:chat_name_slug>/get_messages', views.get_messages, name='get_messages'),
    path('chatroom/<slug:chat_name_slug>/send_message', views.send_message, name='send_message'),
    path('chatroom/<slug:chat_name_slug>/remove_member/<str:username>', views.remove_member, name='remove_member'),
    path('chatroom/<slug:chat_name_slug>/add_member/<str:username>', views.add_member, name='add_member'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User as DjangoUser
from django.template.defaultfilters import slugify
from django.utils import timezone
from allauth.account.signals import user_signed_up
from django.dispatch import receiver

USERNAME_LEN = 30
DISPLAY_NAME_LEN = 50
CHAT_NAME_LEN = 50
CHAT_DESCRIPTION_LEN = 240

class UserProfile(models.Model):
    user = models.OneToOneField(DjangoUser, on_delete=models.CASCADE)
    display_name = models.CharField(max_length=50)
    picture = models.ImageField(upload_to = 'profile_images/', blank=True, default='uploadpics/logo.png')

    def __str__(self):
        return self.user.username

class Chat(models.Model):
    name = models.CharField(max_length=50, unique=True)
    description = models.CharField(max_length=240)
    users = models.ManyToManyField(UserProfile, related_name="chats")
    owner = models.ForeignKey(UserProfile, on_delete = models.CASCADE, related_name= 'chats_owned')
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to = 'chat_images/', blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Chat, self).save(*args, **kwargs)
    def __str__(self):
        return self.name

class Message(models.Model):
    ID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    content = models.TextField()
    #display_name = models.ForeignKey(UserProfile,  on_delete= models.CASCADE, related_name = 'sender_name')#Why is this needed?
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(UserProfile, on_delete= models.CASCADE, related_name= 'sender')
    time_stamp = models.DateTimeField(default=timezone.now())

    def save(self,*args,**kwargs):
        self.time_stamp= timezone.now()
        super(Message,self).save(*args,**kwargs)

    def __str__(self):
        return f"\"{self.content}\""

class File(models.Model):
    ID = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=256)
    data = models.FileField(upload_to = 'chat_files')
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.name = self.data.name
        super(File,self).save(*args,**kwargs)

@receiver(user_signed_up, sender=DjangoUser)
def user_signed_up(request, user, **kwargs):
    u=UserProfile.objects.get_or_create(user=user)[0]
    u.display_name=user.first_name+user.last_name
    u.save()

chat/forms.py
from django import forms
from django.contrib.auth.models import User

from chat.models import UserProfile, Chat, File
from django.contrib.auth.forms import UserChangeForm


class UserForm(forms.ModelForm):
    password = forms.CharField(widget = forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username','password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('display_name', 'picture')


class ChatForm(forms.ModelForm):
    name = forms.CharField(max_length=100, help_text="Please enter the chat name.")
    description = forms.CharField(max_length=300, help_text="Please enter a description of the chat.") # far from finished but made a start 
    image = forms.ImageField(required=False)
    users = forms.ModelMultipleChoiceField(queryset=UserProfile.objects.all())
    owner = forms.ModelChoiceField(queryset=UserProfile.objects.all())

    class Meta:
        model = Chat
        fields = ('name', 'description', 'image', 'users', 'owner')
        
class FileForm(forms.ModelForm):
    
    class Meta:
        model = File
        #need to fix name as it gets overwritten with actual file name
        
        
        #to bootstrap
        # widgets = {
        #     'data': forms.FileField(attrs= {'class':'form-control'})
        # }
        # can do the same to make labels with a labels dict
        
        fields = ['data'] 
        
class ChangeUserDisplayName(forms.ModelForm):
    class Meta:
        model = UserProfile
        widgets = {
            'display_name' : forms.TextInput(attrs= {'class':'form-control mt-2', 'placeholder' : 'Enter a new display name.'})
        }

        labels = {
            'display_name' : ''
        }
        fields = ['display_name']
        
  
class ChangeUserProfilePic(forms.ModelForm):
    class Meta:
        model = UserProfile
        widgets = {
            'picture' : forms.ClearableFileInput(attrs= {'class':'form-control mt-2', 'placeholder' : 'Upload a new profile picture'})
        }
        fields = ['picture']
        labels = {
            'picture' : ''
        }

chat/views.py
import json
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from chat.models import Chat, File, UserProfile, Message, DjangoUser
from chat.forms import ChangeUserDisplayName, FileForm, UserForm, UserProfileForm, ChatForm, ChangeUserProfilePic


@login_required
def search_profiles(request):
    context_dict = {}
    
    if request.method == "POST":
        searched = request.POST['searched']
        profiles = UserProfile.objects.filter(display_name__contains=searched)
        context_dict['searched'] = searched
        context_dict['profiles'] = profiles
        return render(request, 'chat/search_profiles.html', context_dict)
    else:
        return render(request, 'chat/search_profiles.html', context_dict)
        

@login_required
def leave_group_chat(request, chat_name_slug):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        chat = Chat.objects.get(slug=chat_name_slug)
    except Chat.DoesNotExist:
        chat = None
    chat.users.remove(user_profile)
    chat.save()
    return redirect(reverse('chat:chat'))


@login_required
def get_user_chats(request):
    context_dict = {}
    try:
        chat_list = []
        for chat in Chat.objects.all():
            for user in chat.users.all():
                if str(user) == str(request.user):
                    chat_list.append(chat)
                    break
        context_dict['chats'] = chat_list
    except:
        context_dict['chats'] = None
    return context_dict

@login_required
def members(request, chat_name_slug):
    context_dict = {}
    try:
        chat = Chat.objects.get(slug=chat_name_slug)
        chat_members = Chat.objects.get(slug=chat_name_slug).users.all()
        chat_owner = chat.owner
        user = UserProfile.objects.filter(user=request.user)
        # chat_image = chat.image #could someone add this to data base
    except:
        chat = None
        chat_members = None
        chat_owner = None
    context_dict['chat_name'] = chat
    context_dict['chat_members'] = chat_members
    context_dict['chat_name_slug'] = chat_name_slug
    context_dict['owner'] = chat_owner
    context_dict['current_user'] = user.get()
    print(user.get(), chat_owner)
    return render(request, 'chat/members.html', context_dict)

@login_required
def remove_member(request, chat_name_slug, username):
    user = DjangoUser.objects.get(username=username)
    userProfile = UserProfile.objects.get(user=user)
    chat = Chat.objects.get(slug=chat_name_slug)
    chat.users.remove(userProfile)
    chat.save()
    Chat.objects.get(slug=chat_name_slug).users.remove(userProfile)
    return redirect(reverse('chat:members', args=(chat_name_slug,)))


@login_required
def add_member(request, chat_name_slug, username):
    try:
        user = DjangoUser.objects.get(username=username)
    except:
        return redirect(reverse('chat:members', args=(chat_name_slug,)))
    userProfile = UserProfile.objects.get(user=user)
    chat = Chat.objects.get(slug=chat_name_slug)
    chat.users.add(userProfile)
    chat.save()
    return redirect(reverse('chat:members', args=(chat_name_slug,)))

@login_required
def delete_account(request):
    try:
        user_profile = UserProfile.objects.get(user=request.user)
        user = DjangoUser.objects.get(userprofile=user_profile)
    except UserProfile.DoesNotExist:
        user = None
    user_profile.delete()
    user.delete()
    return redirect(reverse('chat:signup'))

@login_required
def delete_group_chat(request, chat_name_slug):
    try:
        chat = Chat.objects.get(slug=chat_name_slug)
    except Chat.DoesNotExist:
        chat = None
    chat.delete()
    return redirect(reverse('chat:chat')) 

@login_required
def files(request, chat_name_slug):
    context_dict = {}
    form = FileForm
    context_dict['form'] = form
    try:
        chat = Chat.objects.get(slug=chat_name_slug)
        user = UserProfile.objects.filter(user=request.user)
        chat_owner = chat.owner
    except:
        chat = None
        user = None
    context_dict['chat_name_slug'] = chat_name_slug
    context_dict['chat_name'] = chat
    context_dict['current_user'] = user.get()
    context_dict['owner'] = chat_owner
    context_dict['files'] = File.objects.filter(chat=chat)
    if request.method == 'POST':
        form = FileForm(request.POST, request.FILES)
        if form.is_valid():
            print('valid form')
            
            file_instance = form.save(commit=False)
            file_instance.chat = chat 
            
            file_instance.save()
            return redirect(reverse('chat:files', kwargs={'chat_name_slug': chat_name_slug}))
        else:
            print(form.errors)
    else:
        form = FileForm()
    return render(request, 'chat/files.html', context_dict)

@login_required
def chat(request, chat_name_slug):
    context_dict = {}
    context_dict['chats'] = Chat.objects.all()
    try:
        this_chat = Chat.objects.get(slug=chat_name_slug)
        owner = this_chat.owner
        context_dict['messages'] = Message.objects.filter(chat=this_chat)
        context_dict['owner'] = owner
        context_dict['chat_name'] = this_chat.name
        context_dict['chat_name_slug'] = this_chat.slug
        context_dict['current_user'] = UserProfile.objects.filter(user=request.user).get()
        context_dict['this_username'] = UserProfile.objects.filter(user=request.user)[0].user.username
    except Chat.DoesNotExist:
        chat = None
    return render(request, 'chat/chat.html', context_dict)

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('chat:chat'))
        else:
            print(f"Invalid login details: {username}, {password}")
            return render(request, "chat/login.html", context={'invalid_login':True})
    else:
        return render(request, "chat/login.html", context={'invalid_login':False})

@login_required
def main_page(request):
    return render(request, "chat/mainpage.html", context=get_user_chats(request))

#@login_required
def send_message(request, chat_name_slug):
    username = request.GET['username']
    content = request.GET['content']
    chat_slug = request.GET['chat_slug']
    chat = Chat.objects.get(slug=chat_slug)
    sender = UserProfile.objects.get(user=request.user)
    if(content):
        m = Message.objects.create(content=content, chat=chat, sender=sender)
        m.save()
    return get_messages(request, chat_name_slug)

#@login_required
def get_messages(request, chat_name_slug):
    chat_slug = request.GET['chat_slug']
    messages = Message.objects.filter(chat=Chat.objects.get(slug=chat_slug))
    messages_list = [{'pic':m.sender.picture.url,'time_stamp':str(m.time_stamp), 'sender':m.sender.user.username, 'content':m.content} for m in messages]
    return HttpResponse(json.dumps(messages_list))

def sign_up(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture  = request.FILES['picture']

            profile.save()

            registered = True
            return redirect(reverse('chat:login'))
        else:
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'chat/signup.html',
                  context={'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered}
                  )#request needs to be added

@login_required
def create_page(request):
    context_dict = {}
    user_profiles = UserProfile.objects.all()
    usernames = [i.user.username for i in user_profiles]
    context_dict['all_users'] = user_profiles
    context_dict['usernames'] = json.dumps(usernames)
    context_dict['current_user'] = json.dumps(request.user.username)
    
    if request.method == 'POST':
        members_str = request.POST.get('user_list')
        try:
            members = json.loads(members_str)
        except:
            members = []
        owner = UserProfile.objects.get(user=request.user)
        chat_form = ChatForm(request.POST, request.FILES)
        user_list = []
        for i in user_profiles:
            if i.user.username in members:
                user_list.append(i)

        if chat_form.is_valid():
            print('valid')
            chat = chat_form.save(commit=False)
            chat.save()
            chat.users.add(owner)
            for i in user_list:
                chat.users.add(i)
            chat.save()
            return redirect('chat:chat')
        else:
            print(chat_form.errors)
    else:
        chat_form = ChatForm()
        
    return render(request,'chat/createchat.html',context=context_dict)

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('chat:login'))#need to add a reverse url

def test(request):
    return render(request,'chat/test.html',context = {})

@login_required
def profile(request):
    context_dict = {}
    pic_form = ChangeUserProfilePic
    display_name_form = ChangeUserDisplayName
    try:
        context_dict['display_name_form'] = display_name_form

templates/chat/Login.html
{% extends 'chat/base.html' %}
{% load staticfiles %}
{% load socialaccount %}

{% block title_block %}
    Login
{% endblock%}

{% block includes_block %}
<link rel="stylesheet" href="{% static 'styles/auth.css' %}">
{% endblock %}

{% block body_block %}
<main class="form-signin w-100 m-auto text-center">
    {% if invalid_login %}

<div class="modal show text-dark">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title">Invalid Login</h1>
        <button type="button" class="btn-close" aria-label="Close" onclick="$('.modal').removeClass('show').addClass('fade');"></button>
      </div>
      <div class="modal-body">
          Invalid login detail were supplied.  Please try again or create an account.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" onclick="$('.modal').removeClass('show').addClass('fade');">Okay</button>
      </div>
    </div>
  </div>
</div>
    {% endif %}
    <div class="card bg-primary">
        <div class="card-body">
            <form id="login_form" method="post" action="{% url 'chat:login' %}">
                {% csrf_token %}
                <img class="mb-4" src="{% static '/images/no_words_logo.png'%}" alt="" width="70" height="70">
                <h1 class="h3 mb-3 fw-normal">Log in</h1>
                <div class="form-floating">
                  <input name="username" type="text" class="form-control bg-secondary text-light mb-1 border-primary-subtle" id="floatingInput" placeholder="Username" required="" autocomplete="off">
                  <label for="floatingInput">Username</label>
                </div>
                <div class="form-floating">
                  <input name="password" type="password" class="form-control bg-secondary text-light mb-2 border-primary-subtle" id="floatingPassword" placeholder="Password" required="" autocomplete="off">
                  <label for="floatingPassword">Password</label>
                </div>
                <button class="w-100 btn btn-lg btn-outline-light" type="submit">Sign in</button>
                <span class="login-text">Don't have an account? <a href="{% url 'chat:signup' %}" class="text-light">Sign up.<a></span>
                <a href="{% provider_login_url 'google'%}?next=/" class="text-light">
                    Login with Google
                </a>
            </form>
        </div>
    </div>
</main>
{% endblock %}

templates/chat/all_chats.html
<!DOCTYPE html>
{% if chats %}
    <a class="list-group-item align-items-center">
        <div class="d-flex w-100 align-items-center">
            <h3 class="mb-1 align-items-center text-truncate">My Chats</h3>
        </div>
    </a>
    {% for chat in chats %}
        {% if chat.name == chat_name %}
            <a href="{% url 'chat:chatroom' chat.slug%}" class="list-group-item list-group-item-action active">
        {% else %}
            <a href="{% url 'chat:chatroom' chat.slug%}" class="list-group-item list-group-item-action">
        {% endif %}
                
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1 text-truncate">{{chat.name}}</h5>
                </div>
                <small class="d-flex justify-content-between fw-lighter text-truncate">{{chat.description}}</small>
            </a>
    {% endfor %}
{% else %}
    <li class="list-group-item list-group-item-info">You are in no chats.</li>
{% endif %}

            
        

templates/chat/chattemplates.html
{% extends 'chat/base.html' %}
{% load staticfiles %}
{% load static %}
{% load chat_template_tags %}


{% block body_block %}
    
        <nav class="navbar navbar-dark" style="background-color: #91b1f7;">
            <div class="container-fluid">
                    <a class="navbar-brand" href="/chat/">
                        <img src="{% static 'images/no_words_logo.png' %}" alt="logo" width="50px" height="auto" class="d-inline-block align-text-center">
                        MyChatGla
                    </a>
                <div class="d-flex">
                    <form class="d-flex" method="POST" action="{% url 'chat:search_profiles' %}">
                        {% csrf_token %}
                        <div class="input-group me-3">
                            <input class="form-control" 
                            type="search" placeholder="Search Display Names" aria-label="Search"
                            name = "searched">
                            <button class="btn btn-outline-light" type = "submit">Search</button>
                        </div>
                    </form>
                    <a id="createChatButton" href="{% url 'chat:create' %}" class="btn btn-outline-light me-1">
                        <i class="bi bi-plus-lg"></i> Create
                    </a>
                    <div class="dropdown">
                        <a class="btn btn-outline-light" type="button" data-bs-toggle="dropdown">
                            <i class="bi bi-person-fill"></i> Profile
                        </a>
                        <ul class="dropdown-menu dropdown-menu-end">
                            <li><a class="dropdown-item" href="{% url 'chat:profile' %}">Settings</a></li>
                            <li><a class="dropdown-item" href="{% url 'chat:logout' %}">Sign Out</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </nav>
    <main style = "height:100%;">
        <div class="container-fluid h-100">
            <div class="row row-tall h-100" style = "background-image: url('static/images/no_words_logo.png')">
                <div class="col col-2 d-none d-md-block bg-primary h-100">
                    <div class="list-group pt-3 h-75 overflow-scroll">
                        {% get_chat_list request chat_name %}
                    </div>
                </div>
                <div class="col ps-0 pe-0 h-100">
                    <div class="pt-3 ps-3 pe-3 pb-0 navbar navbar-expand-lg bg-tertiary" style="background-color:var(--bs-tertiary);">
                        {% block content_title %}
                        {% endblock %}
                    </div>

                    <div class="container-fluid p-3 h-75">
                    {% block content_block %}
                    {% endblock %}
                    </div>
                </div>
        </div>
    </main>
{% endblock %}

templates/chat/members.html
{% extends 'chat/roomtemplate.html'%}
{% load staticfiles %}

{% block title_block %}
    Members
{% endblock %}

{% block includes_block %}
<script src="{% static 'js/addMember.js' %}"></script>
{% endblock %}

{% block content_name %}
- Members
{% endblock %}

{% block content_block %}

<div style="margin-right: 5rem;">
    <div class="container-fluid outerbox">
        <div class="row justify-content-center align-items-top g-2">
            <div class = "col colpadding">
                <div class="membercol">
                    {% if current_user == owner %}
                        <label for="ChatName" class="form-label">Add Member</label>
                        <div class="input-group">
                            <input type="text" class="form-control" id="memberInput" placeholder="Enter Member Username">
                            <button type="button" id="addMemberButton" class="btn btn-primary" onclick="addMember()" id="addMemberButton">Add</button>
                        </div>
                    
                    {% else %}

                    <h2>Only Owners can add new members</h2>
                    <p>If you would like to add someone.<br>Please contact {{ owner }}</p>
                    {% endif %}
                    
                </div>
            </div>


            <div class="col colpadding">
                <h3>Owner: </h3>
                <ul class="list-group">
                    <li class="list-group-item">{{ owner.display_name }} ({{owner}})</li>
                </ul>
                <h5>Members </h5>
                <ul class="list-group scrollable">
                    {% for user in chat_members %}
                        {% if user != owner %}
                        <li class="list-group-item">
                            {{ user.display_name }} ({{user}}) {% if current_user == owner %}<a class="btn btn-close float-end" href="{% url 'chat:remove_member' chat_name_slug=chat_name_slug username=user.user.username %}"></a> {% endif %}
                        </li>
                        {%endif%}
                        {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/chat/profile.html
{% extends 'chat/chattemplates.html'%}
{% load staticfiles %}

{% block title_block %}
    Profile
{% endblock %}

{% block content_title %}
<nav class="navbar bg-tertiary w-100">
    <div class="container-fluid">
        <h2 class="text-light" href="#">My Profile - {{current_user}}</h2>
    </div>
  </nav>
{% endblock %}

{% block content_block %}
<div class="container-fluid box-size">
    <div class="row justify-content-center align-items-center g-2">
        <div class="col">
            {% if current_user.picture %}
            <img class="rounded-circle ms-2" width="200" height="200" src="{{current_user.picture.url}}"alt = "chat image">
        </div>
        {% else %}
        <img src="{% static 'images/classhat.jpg' %}" class="card-img-top rounded object-fit-cover" alt="" width="200px" height="200px"></div>
            {% endif %}

        <div class="col membercol">
            <ul style="list-style-type:none; font-size:30px">
                <li>Name: {{current_user}}</li>
                <li>Display name: {{current_user.display_name}}</li>
            </ul>
        </div>
    </div>
    <div class="row justify-content-between align-items-center g-2">
        <div class="col align-items-center">
            <form method="post">
                <div class="input-group">
                <input type="hidden" name="form_type" value="display_name_form">
                {% csrf_token %}
                {{ display_name_form }}
                <input type="submit" value="Submit" class ="btn btn-secondary mt-2" />
                </div>
            </form>
            <form method="post" enctype="multipart/form-data">
                <div class="input-group">
                <input type="hidden" name="form_type" value="pic_form">
                {% csrf_token %}
                {{ pic_form }}
                <input type="submit" value="Submit" class ="btn btn-secondary mt-2" />

                </div>
            </form>
        <a class="btn btn-danger d-block mt-5" href="#" data-bs-toggle="modal" data-bs-target="#deleteAccountModal">Delete Account</a>
        </div>
    </div>
</div>
<div class="modal fade" id="deleteAccountModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Are you sure you want to delete your account?</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</a>
        <a type="button" class="btn btn-danger" href="{% url 'chat:delete_account' %}">Delete Account</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/chat/roomtemplate.html
{% extends 'chat/chattemplates.html' %}
{% load staticfiles %}

{% block content_title %}
{{ this_username|json_script:"this-username" }}
{{ chat_name_slug|json_script:"chat-slug" }}
<nav class="navbar bg-tertiary w-100">
  <div class="container-fluid">
      <h2 class="text-light" href="#">{{chat_name}}{% block content_name %} {% endblock %}</h2>
    <div class="d-flex" id="navbarText">
      <ul class="navbar-nav flex-row me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active text-light" aria-current="page" href="{% url 'chat:chatroom' chat_name_slug%}">Home</a>
        </li>
        <li class="nav-item">
            <a class="nav-link text-light" href="{% url 'chat:members' chat_name_slug %}">Members</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-light" href="{% url 'chat:files' chat_name_slug %}">Files</a>
        </li>
{% if current_user == owner %}
        <li class="nav-item">
            <!--<a class="nav-link text-light" href="{% url 'chat:delete' chat_name_slug %}">Delete</a>-->
            <a class="nav-link text-light" href="#" data-bs-toggle="modal" data-bs-target="#deleteLeaveModal">Delete</a>
        </li>
{% else %}
        <li class="nav-item">
            <a class="nav-link text-light" href="#" data-bs-toggle="modal" data-bs-target="#deleteLeaveModal">Leave</a>
        </li>
{% endif %}
      </ul>
    </div>
  </div>
</nav>
<div class="modal fade" id="deleteLeaveModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
{% if current_user == owner %}
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Are you sure you want to delete this chat?</h1>
{% else %}
        <h1 class="modal-title fs-5" id="staticBackdropLabel">Are you sure you want to leave this chat?</h1>
{% endif %}
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</a>
{% if current_user == owner %}
        <a type="button" class="btn btn-danger" href="{% url 'chat:delete' chat_name_slug %}">Delete Chat</a>
{% else %}
        <a type="button" class="btn btn-primary" href="{% url 'chat:leave' chat_name_slug%}">Leave Chat</a>
{% endif %}
      </div>
    </div>
  </div>
</div>
{% endblock %}